import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import "./app.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { AuthProvider } from "@/context/AuthContext";

import { Sora } from "next/font/google";

const sora = Sora({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="transition-colors duration-300 text-black dark:text-white"
      suppressHydrationWarning
    >
      <body className="bg-cream">
        <ThemeProvider>
          <AuthProvider>
            <Navbar />
            <main
              className={`bg-cream mx-auto px-4 sm:px-6 lg:px-8 py-4 ${sora.className}`}
            >
              {children}
            </main>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
